name: public-speaking-coach-agent
version: 1.0.0
description: AMD Cloud Agent for Public Speaking Coach NLP analysis

runtime:
  type: python
  version: "3.11"

agent:
  name: PublicSpeakingCoachAgent
  entry_point: agent.main_agent.run_agent
  
tools:
  - name: adk_nlp_analysis
    module: agent.tools.adk_nlp_tool
    function: adk_nlp_analysis
    description: Analyzes speech transcripts for clarity, filler words, and provides improvement suggestions

environment:
  variables:
    - FIREBASE_KEY_PATH
    - FIREBASE_STORAGE_BUCKET
    - WHISPER_MODEL_SIZE
    - WHISPER_DEVICE
    - WHISPER_COMPUTE_TYPE

requirements:
  - faster-whisper>=0.9.0
  - firebase-admin>=6.0.0
  - fastapi>=0.104.0
  - uvicorn>=0.24.0
  - python-multipart>=0.0.6
  - aiofiles>=23.0.0

deployment:
  platform: google-cloud-run
  region: us-central1
  min_instances: 0
  max_instances: 10
  cpu: 2
  memory: 4Gi
  timeout: 300s

